### ISSUE TITLE
Subscribing to two topics with different Microflows

### ISSUE THREAD

**Issue by simo101** [ako/MqttClient#1]
Hi Andrej,

I have been using this module with one topic quite successfully. I included it into my after startup and successfully subscribed to my mosquitto topic.

However now i want to subscribe Mendix to the second topic with a different microflow. When i do this it seems that the first topic will execute my second microflow, which is meant for the second topic.

Is the idea that you have one microflow for every subscribed topic? Hence why you have an input parameter in the microflow called topic? Do i have to use the topic to decide what to do with the input?

Or is this a bug and i should be able to add different microflows to each microflow.

Regards
Simon

**Comment by ako** [comment]
Hi Simon,

It's a bug, I've committed a fix.

Regards,
Andrej

**Comment by simo101** [comment]
Thanks Andrej. I will update my app and test. In the meantime I just put a check in my microflow to check the topic input. Other than that it seems to be working pretty well so far.
